#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd frontend
yarn lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
) &

npx lint-staged